name: Lint

on: push

jobs:
  run-test-lint:
    name: Run tests and linter
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        gemfile: ['Gemfile']

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Run Rubocop
        uses: wearerequired/lint-action@v1
        with:
          rubocop: true
          rubocop_command_prefix: bundle exec

      - name: Run specs
        run: bundle exec rake spec

